### PR TITLE
fixing attendance and add filter by status

### LINKED ISSUE #39: Fixing Attendance Feature
Edit Response Get, And Add Filter by Status

### PR DESCRIPTION
**Pull request by fajar2302**

### CODE REVIEW

File: features/Attendance/handler/handler.go [hunk 1]
```diff
@@ -138,35 +138,43 @@ func (ah *AttHandler) GetAttendancesHandler(c echo.Context) error {
...
+		attDetail, err = ah.srv.GetAttByPersonalID(uint(attId), searchBox, limit, offset)
+		if err != nil {
+			return c.JSON(http.StatusInternalServerError, map[string]string{"error": err.Error()})
+		}
+		for _, detail := range attDetail {
+			responseDetail = append(responseDetail, ToGetAttendanceResponse(detail))
+		}
+		result = responseDetail
 	}
+	fmt.Println("Data-Handler: ",result)
```
Comment (jackthepanda96) [inline features/Attendance/handler/handler.go]: kalo ga dipake dihapus aja

**Review by jackthepanda96 — CHANGES_REQUESTED** [review]

**Review by jackthepanda96 — APPROVED** [review]

**Review by riandarmawann — APPROVED** [review]
